version: '3.9'

services:
  mariadb:
    container_name: AICup_mariadb
    image: mariadb:10.10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ikm@903
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3307:3306

  phpmyadmin:
    container_name: AICup_phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8083:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db:

  # redis:
  #   container_name: AICup_redis
  #   image: redis:6
  #   networks:
  #     - directus

  # directus:
  #   container_name: AICup_directus
  #   image: directus/directus:latest
  #   ports:
  #     - 8055:8055
  #   volumes:
  #     # By default, uploads are stored in /directus/uploads
  #     # Always make sure your volumes matches the storage root when using
  #     # local driver
  #     - ./uploads:/directus/uploads
  #     # Make sure to also mount the volume when using SQLite
  #     # - ./database:/directus/database
  #     # If you want to load extensions from the host
  #     # - ./extensions:/directus/extensions
  #   networks:
  #     - directus
  #   depends_on:
  #     - redis
  #     - mariadb
  #   environment:
  #     KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
  #     SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

  #     DB_CLIENT: 'pg'
  #     DB_HOST: 'database'
  #     DB_PORT: '5432'
  #     DB_DATABASE: 'ikm@aicup'
  #     DB_USER: 'ikm@aicup'
  #     DB_PASSWORD: 'ikm@903'

  #     CACHE_ENABLED: 'true'
  #     CACHE_STORE: 'redis'
  #     CACHE_REDIS: 'redis://cache:6379'

  #     ADMIN_EMAIL: 'admin@example.com'
  #     ADMIN_PASSWORD: 'ikm@903'

  #     # Make sure to set this in production
  #     # (see https://docs.directus.io/self-hosted/config-options#general)
  #     # PUBLIC_URL: 'https://directus.example.com'

# networks:
#   directus: